AWSTemplateFormatVersion: '2010-09-09'
Description: Grant read-only access to a specific AWS account

Resources:
  ReadOnlyCrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ReadOnlyCrossAccountAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::138001055538:root'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'

Outputs:
  RoleArn:
    Description: 'ARN of the ReadOnly IAM Role'
    Value: !GetAtt ReadOnlyCrossAccountRole.Arn